<?php

namespace Hz\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccessoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessoryRepository extends EntityRepository{
	public function getByMachineId($machine_id){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a.id, a.type, a.comments FROM HzStoreBundle:Accessory a 
                WHERE a.machine = :machine_id'
            )
            ->setParameter('machine_id', $machine_id)
            ->getResult();
	}
}
