<?php

namespace Hz\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{

	public function search($term) {
		return $this->getEntityManager()
            ->createQuery(
                'SELECT c.id, c.firstname, c.lastname, c.email, c.phone, c.suburb,  c.company
                FROM HzStoreBundle:Customer c 
                WHERE c.firstname LIKE :term OR c.lastname LIKE :term OR c.email LIKE :term
                OR c.phone LIKE :term OR c.suburb LIKE :term OR c.company LIKE :term'
            )
            ->setParameter('term', '%'.$term.'%')
            ->getResult();
	} 
}
